version: '3'

services:
  tg-forward:
    build: .
    image: tg-forward:latest
    container_name: tg-forward
    volumes:
      - /volume1/common/project/tg-forward:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped